---
- name: git checkout project
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ local_dir }}"
    version: '{{ git_commit_head }}'

- name: execute pipeline
  block:
    - name: execute stages
      ansible.builtin.shell:
        chdir: "{{ local_dir }}"
        cmd: "{{ item.1.cmd }}"
      loop: "{{ stages|subelements('jobs') }}"
      run_once: true
      register: echo
  always:
    - name: record logs
      become: no
      delegate_to: localhost
      run_once: true
      copy:
        content: "{{ echo }}"
        dest: "{{ log_dir }}"