---
- name: git checkout 
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ local_dir }}"
    version: 'cbd005a3b1dae0864421fe0f78e94ab2893695d3'

- name: loop
  ansible.builtin.debug:
    msg: "{{ item.1.cmd }}"
  loop: "{{ stages|subelements('jobs') }}"
