---
- name: run any project template
  hosts: all
  vars_files:
    - vars/{{ project_id }}.yaml
  become: true
  tasks:
    - name: git checkout 
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ local_dir }}"
        version: '{{ git_commit_head }}'

    - name: execute pipeline
      block:
        - name: loop stage
          ansible.builtin.shell:
            chdir: "{{ local_dir }}"
            cmd: "{{ item.1.cmd }}"
          loop: "{{ custom_stages|subelements('jobs') }}"
          register: echo
      always:
        - name: record fail
          become: no
          delegate_to: localhost
          copy:
            content: "{{ echo }}"
            dest: "{{ log_dir }}"