---
- name: run pipeline
  hosts: '{{ host_name }}'
  vars_files:
    - vars/{{ project_id }}.yaml
  become: true
  roles:
    - role: ansible-role-git
    - role: ansible-role-nodejs
      when: stack == 'Nodejs'
    - role: ansible-role-java
      when: stack == 'Java'
    - role: ansible-role-maven
      when: stack == 'Java'
    - role: execute-pipeline