---
- name: git checkout 
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ local_dir }}"
    version: '{{ git_commit_head }}'

- name: loop
  ansible.builtin.shell:
    chdir: "{{ local_dir }}"
    cmd: "{{ item.1.cmd }}"
  loop: "{{ stages|subelements('jobs') }}"
  when: use_standard_ci

- name: loop
  ansible.builtin.shell:
    chdir: "{{ local_dir }}"
    cmd: "{{ item.1.cmd }}"
  loop: "{{ custom_stages|subelements('jobs') }}"
  when: not use_standard_ci